version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: stacy_store_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
     build:
       context: .
       dockerfile: Dockerfile
     environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/stacy_store_db
       SPRING_DATASOURCE_USERNAME: postgres
       SPRING_DATASOURCE_PASSWORD: password
     ports:
       - "9090:9090"
     depends_on:
       - db

volumes:
  postgres_data: