server:
  port: 9090
  servlet:
    context-path: /store-api

spring:
  application:
    name: StoreAPI
  datasource:
    url: jdbc:postgresql://db:5432/stacy_store_db
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false

logging:
  level:
    liquibase:
      INFO

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger